// <auto-generated />
namespace StudentAttendence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig112));
        
        string IMigrationMetadata.Id
        {
            get { return "201904280427403_mig112"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
